describe("stealth starting", ()=>{
    beforeEach(()=>{
        cy.visit("http://localhost:3007/")
    })
    it("login",()=>{
        cy.get('#email').type('waseem.ullah@dealershiptoolkit.com')
        cy.get('#password').type('Allah@1.')
        cy.get('#login').click()
        cy.contains('Appointments').click()
        cy.contains('Create Appointment').click()
        //cy.get('#email').click().type('shahrukh.asghar@datics.ai')
        cy.get('#createCustomerButton').click()
        cy.get('#createAppointmentButton').click()
        cy.get('#firstName').type('shahrukh')
        cy.get('#lastName').type('Asghar')
        cy.get('#email').type('shahrukh.asghar+41@datics.ai')
        cy.get('[type="submit"]').click()
        cy.get('.MuiDialogContent-root').first().then(form =>{
            cy.wrap(form).find('#franchiseId').click()
           // cy.contains('Heflin').click()
           cy.get('.MuiPopover-paper .MuiList-root').contains('Heflin').click({force:true})
            cy.wrap(form).find('#autoYear').type('2023')
            cy.wrap(form).find('#autoMake').type('Toyota')
            cy.wrap(form).find('#autoModel').type('XLI')
            cy.wrap(form).find('#autoVin').type('84749652F')
            cy.wrap(form).find('#nextButton').click()
        })
        cy.get('.MuiDialogContent-root').last().then(details =>{
            cy.wrap(details).find('#category').click()
            cy.get('.MuiPopover-paper .MuiList-root').eq(1).contains('New Sale').click({force:true})
            cy.wrap(details).find('.MuiOutlinedInput-root #notes').type('testing automation')
          //  cy.wrap(details).contains('Notify Dealership').click({force:true})
           // cy.wrap(details).find('#nextButton').click({force:true})
        })
    })
})